//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCDrd.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Post
    {
        public Post()
        {
            this.PostTags = new HashSet<PostTag>();
        }
    
        public long id { get; set; }
        public System.DateTime date { get; set; }
        public string title { get; set; }
        public string post1 { get; set; }
        public Nullable<int> image { get; set; }
        public Nullable<short> user { get; set; }
    
        public virtual ICollection<PostTag> PostTags { get; set; }
        public virtual Image Images { get; set; }
    }
}
